### ISSUE TITLE
On Spanish site, link to the "Markdown help" page links to a different page.

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#14]
Instead, it links to the following old page:

<img width="1225" alt="screen shot 2016-06-02 at 16 25 03" src="https://cloud.githubusercontent.com/assets/19697899/15761622/d716c1ca-28de-11e6-984b-08f32fc9e5e0.png">

**Comment by contreras-jorgev** [comment]
We forgot to add it. It was finding the "next" most-similar table-name.

It works now.
