### ISSUE TITLE
On templates, use the ** markdown instead of ## to show the "questions" in bold

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#18]
Currently, the "questions" in templates are too large in size because the ## markdown is being used. In order to keep the "questions" and "answers" the same size, use the *\* markdown to simply to show the questions in bold.

**Comment by contreras-jorgev** [comment]
Note: The code is fixed, but the we will wait to deploy it later tonight (to avoid disturbing your work).
