### ISSUE TITLE
Add a little disclaimer when edit/create Tables telling user that in order for Preview to work, Pop-ups need to be enabled.

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#19]
After editing a table, I pressed the "Preview" button and nothing happened.

**Comment by contreras-jorgev** [comment]
Change your Safari preferences:

![blockpop](https://cloud.githubusercontent.com/assets/7340244/15795616/ec9bdfdc-29b8-11e6-9467-50e084ce4c4b.png)

To remove "Block pop-up windows'.

Note: We may overcome that limitation (later) with a little window like we did for iPhone ...

**Comment by contreras-jorgev** [comment]
It seems to be working after unblocking pop-up windows.

**Comment by FernandoContrerasPalomar** [comment]
We should leave this one open as an "enhacement". It may not be obvious to the user that this feature doesn't work if the pop-up blocker is enabled.
