### ISSUE TITLE
Unable to delete an empty line within a row in a table

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#23]
I was unable to remove the empty line above "Resumen para executivos". The delete key wouldn't let me get rid of it.

<img width="1230" alt="screen shot 2016-06-03 at 19 14 35" src="https://cloud.githubusercontent.com/assets/19697899/15796206/ac3de334-29bf-11e6-85bf-8e484d2539eb.png">

**Comment by contreras-jorgev** [comment]
I believe something went wrong when converting the table from V1 (the new-line character must have been placed in the wrong position). There will be no more import (and I don't think there will be a way get to this state when creating new tables).

The workaround I found (I removed the empty line already):
- Add a blank character before `* Resumen`

![fer23](https://cloud.githubusercontent.com/assets/7340244/15898483/21967a64-2d5e-11e6-91d9-ae623b27b650.png)
- Move cursor to the asterisk, and use "Backspace" three times to remove the blank AND the line above.
