### ISSUE TITLE
Bullets in front of bold text don't work

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#28]
I tried to add bullets in front of text in bold, by using: \* **.

Example (from Alzheimer table in Spanish)

<img width="1092" alt="screen shot 2016-06-06 at 16 42 19" src="https://cloud.githubusercontent.com/assets/19697899/15838824/b972accc-2c05-11e6-986e-7e16e9005797.png">

Unfortunately, this doesn't yield the expected result. The bullets don't show up.

Am I doing something wrong?

**Comment by contreras-jorgev** [comment]
Same as #30  (need blank line before starting bullet list)

```
* **Edad**: El riesgo mayor de desarrollar la enfermedad es la edad.  

* **Genética**: Si bien el Alzheimer no tiene causa conocida y no muestra patrón de herencia evidente, en algunas familias se ven grupos de casos.  

```

Produces: 

![preview](https://cloud.githubusercontent.com/assets/7340244/15841429/e10e9866-2c16-11e6-990c-bda3375b063a.png)
