### ISSUE TITLE
Markdown is showing italics instead of bullets

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#30]
I am trying to use \* to show bullets, but it is showing italics instead:

Example (in Autismo table in Spanish):

<img width="1210" alt="screen shot 2016-06-06 at 16 55 44" src="https://cloud.githubusercontent.com/assets/19697899/15839234/de771042-2c07-11e6-9a9a-886f53e8d0f0.png">

The markdown code:

<img width="1189" alt="screen shot 2016-06-06 at 16 59 07" src="https://cloud.githubusercontent.com/assets/19697899/15839255/04476f10-2c08-11e6-9b55-bd03064adff0.png">

**Comment by FernandoContrerasPalomar** [comment]
The Brownies table in Spanish has the same issue within the "ingredientes" section

**Comment by FernandoContrerasPalomar** [comment]
I tried using "-" and "+" instead of "*", but the markdown simply showed the raw characters (i.e. + or -). It seems something is broken regarding bulleted lists.

**Comment by contreras-jorgev** [comment]
We are using open-source module: 
     https://www.npmjs.com/package/markdown (https://github.com/evilstreak/markdown-js)

to convert the text to HTML using markdown rules.

We are using the default option. The developer talks about two Markdown dialects: "Gruber", "Maruku"
We assumed that the "dialect" that I documented corresponded to the default dialect.

There is also the possibility that this module has issues ... I'll research.
Depending on what I find, we can:
    \* Use a different open source module to do the conversion.
    \* Fix the current open-source.
    \* If the module works as designed, we may be using the wrong dialect (on our documentation).

I would like to use the "most popular" dialect, for sure one that is compatible with Wikipedia and Whatsup.

I'll research and post my findings.

**Comment by contreras-jorgev** [comment]
Looks like all we need is a blank line starting the bullet list and before each bullet item:

```
**Causas**  
FACTORES GENÉTICOS:  
El autismo es el trastorno más genético de los síndromes neurosiquiátricos. Es, primordialmente, la consecuencia de la alteración de un conjunto de genes interdependientes, distribuidos en distintos puntos del genoma, siendo necesaria la participación de un número mínimo de genes, para su desarrollo y aparición.  
FACTORES AMBIENTALES.  

* Complicaciones obstétricas. Sin ser la causa básica del autismo, puede ser un agravante por los posibles trastornos asociados (discapacidad intelectual, crisis epilépticas, trastornos de conducta, y otros) debido a la interacción genética.  

* Enfermedades tóxicas. Se ha estudiado la exposición intrauterina a diversos agentes tóxicos como el ácido valproico y otros antiepilépticos, la cocaína, el alcohol, el plomo, la exposición crónica de la madre y el feto a niveles bajos de monóxido de carbono y otros, con conclusiones no siempre coincidentes.  
```

Note: after each bullet list I have two blanks (this is explained in the Help)

![preview](https://cloud.githubusercontent.com/assets/7340244/15841310/edd7c744-2c15-11e6-864f-1c360ff066e4.png)

**Comment by FernandoContrerasPalomar** [comment]
Good catch! Thanks!

Can you please add comments in the help pages (Spanish and English) explaining that one must add an empty line before the bullets? This was done for "Lists" but not for "Bullets".

**Comment by contreras-jorgev** [comment]
Added comments to the help pages (paragraph describing bullet lists).
