### ISSUE TITLE
Need text (English and Spanish) for implementation of Delete warning

### ISSUE THREAD

**Issue by contreras-jorgev** [Tablepedia/V2-Beta#31]
Related to Issue # 22

Please provide text (both languages), the warning looks something like:

![ferwarning](https://cloud.githubusercontent.com/assets/7340244/15842635/7d46b660-2c20-11e6-8423-f5b72e647a96.png)

Note: also note that the buttons on the Edit page were moved around such that "DAR DE BAJA" is now to the left (more difficult to be hit by mistake)

**Comment by FernandoContrerasPalomar** [comment]
Here are the texts:

English:
"You are about to delete the XXXX table. Once deleted, it cannot be recovered. 

Are you sure you want to proceed?"

Spanish:
"Estás a punto de eliminar la tabla XXXXX. Una vez eliminada, no se puede recuperar. 

Estás seguro de que la quieres eliminar?"

**Comment by contreras-jorgev** [comment]
Fixed. Will be deployed shortly
