### ISSUE TITLE
The "Register" dialog asking for e-mail can be presented in three different ways ... may be confusing

### ISSUE THREAD

**Issue by contreras-jorgev** [Tablepedia/V2-Beta#56]
Ways to get to dialog that says "Register ... Creating tables is coming soon!":
1. Tap/Click on "Sign-In" (Identificarse), then on click on "Register".
2. From a Table content, Tap/Click on Edito button, then on click on "Register".
3. Add a Table, then click on "Register".

All of these show: Creating tables is coming soon!

Should we make the text on dialog different? or,
Should we change the text to cover all cases, something like:

"Full access coming soon! - adding and editing tables requires a registered user ... blah, blah"

**Comment by FernandoContrerasPalomar** [comment]
I like the idea about making a common "full access coming soon" site. I'll work on that.
