### ISSUE TITLE
Review meta name="description" on all pages (both sites English, Spanish)

### ISSUE THREAD

**Issue by contreras-jorgev** [Tablepedia/V2-Beta#73]
Google recommendation:

https://support.google.com/webmasters/answer/79812?hl=en
What we have today:  
- Spanish:  
  meta name="description" content="El nuevo sitio en la web que ofrece información básica, condensada y práctica sobre cualquier tema en formato de Tabla.”
  meta name="description" content="Los colaboradores de Tablepedia aportan tablas con contenido untracondensado sobre cualquier tema.”
- English:  
  meta name="description" content="The new free website that provides basic condensed information about a wide range of topics using a simple Table format that is easy to read and digest.”

Note: We actually have some Spanish on the english site !

**Note**: On the www.tablepedia.com we may need BOTH languages (?), because this page is Bilingual? — Fer, please research if we can have more than one language for “meta name:description”

**Comment by contreras-jorgev** [comment]
I have assigned to you, to design the "slogan" we want, but twill start at least making sure we are consistent with what we currently have.

**Comment by FernandoContrerasPalomar** [comment]
For the language selector and the main english site: "Share your knowledge using a simple Table format".

For the the spanish site: "Comparte tu sabiduría utilizando un sencillo formato de Tabla."

I did a bit of research of differentiation of tags based on language, and it doesn't seem simple. Let's just go for the hardcoded descriptions for now.

**Comment by contreras-jorgev** [comment]
All pages updated. (But not published yet)
