### ISSUE TITLE
Create account - if password is too short, the "Register" button does nothing

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#74]
To reproduce: In the create account page, specify a valid name and e-mail address. Then, enter a short password and try to press "Register". Nothing will happen. It seems like an error message was not defined for such scenario.

I encountered the same issue for the English and Spanish sites

**Comment by contreras-jorgev** [comment]
Fixed. It now shows some suggestions (depending on what you type), for example if the password given is just "a", you will now see:

![simulator screen shot jul 18 2016 6 22 22 pm](https://cloud.githubusercontent.com/assets/7340244/16933628/e326da90-4d14-11e6-8b08-1023aa93b82f.png)

Note: We will deploy the fix tonight.
