### ISSUE TITLE
Create account - URL is deemed invalid if it doesn't have http or https prefix

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#75]
I got an invalid URL message when I entered the URL as: www.facebook.com/fercontreras8. The message didn't explain why the URL was invalid. I added the http:// prefix and then it worked. Is there a way to validate the URL without requiring such prefix?

**Comment by contreras-jorgev** [comment]
We are passing the URL to an open-source module. What we'll try to do is, that if it returns as failed, check for the protocol (https, or http), if it is not there pre-pend it, and try again. If it works, we can add the prefix to the URL provided (and remember it as such).

**Comment by contreras-jorgev** [comment]
Note: We will deploy shortly ...
