### ISSUE TITLE
Checkbox not aligned on android browser.

### ISSUE THREAD

**Issue by willianet97** [Tablepedia/V2-Beta#78]
The last checkbox (accepting terms and conditions) isn't alligned with the corresponding label.
![screenshot_20160718-192852](https://cloud.githubusercontent.com/assets/16727246/16934654/fffd4a56-4d1d-11e6-8790-acd460478c18.png)

**Comment by contreras-jorgev** [comment]
I can reproduce using iPhone 5 (my phone) -- Should also happen using iPhone 5 simulator.

**Comment by contreras-jorgev** [comment]
Check also checkbox "Receive marketing e-mails from Tablepedia"

Maybe instead of shortening the text, we can use wrapping (two lines instead on one, on small phones?)
