### ISSUE TITLE
if user's URL doesn't include "http" prefix, it links to the wrong URL

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#83]
I specified my URL as "www.facebook.com/fercontreras8". If you go to one of my tables (i.e. "Dimmer") and you click on my URL's link, you'll see that it is linking to a URL within Tablepedia:

https://en.tablepedia.com/www.facebook.com/fercontreras8

I was able to work around this issue by explicitly entering "https://" as a prefix to my URL. That made the issue "go away".

**Comment by contreras-jorgev** [comment]
Will update the Alpha server shortly.
Please re-test.

Note: The Beta does not have the fix ...

**Comment by FernandoContrerasPalomar** [comment]
Re-tested and it works properly
