### ISSUE TITLE
User preferences are not fully updated on public site

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#84]
I used the alpha site to update my preferences, specifying that I wanted to show my name and e-mail on my tables. If you go to one of my tables (i.e. "Dimmer") using the alpha site, such settings are reflected appropriately. However, if you go to the public site, my tables don't show my name nor my e-mail. They only show my website's URL.

**Comment by contreras-jorgev** [comment]
The Beta site will be updated with the new code, when we decide to add the Registration + User Profile features. This issue will go away by then. Please re-test only using Alpha sites.

Note: We are being careful not to break the Beta site, but are not too concerned about fixing issues that are already working on Alpha.
