### ISSUE TITLE
Improve the style of the Reference box.

### ISSUE THREAD

**Issue by contreras-jorgev** [Tablepedia/V2-Beta#85]
1. Un laptop, desktop & wide it does not show correctly.
2. Make border color, radius consistent with table row's style.
3. Remove "resize" icon.

**Comment by FernandoContrerasPalomar** [comment]
4 - Show the box below the "References" title. Currently, in the desktop version, the box appears to the right of the title

**Comment by contreras-jorgev** [comment]
Please re-test after we update the Alpha sites. We'll notify you.
