### ISSUE TITLE
Sign-in dialog box does not look as nice on Safari (desktop) as it does on iPhone

### ISSUE THREAD

**Issue by contreras-jorgev** [Tablepedia/V2-Beta#86]
![screen shot 2016-08-10 at 7 37 26 pm](https://cloud.githubusercontent.com/assets/7340244/17575785/ffa05faa-5f31-11e6-855f-d08850ea9aca.png)

**Comment by willianet97** [comment]
Changed background color to white, need revision to see if it is nice like that.
