### ISSUE TITLE
When selecting "Eliminar Tabla" (Spanish site), the options (cancel or proceed) are listed in English

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#87]
<img width="452" alt="screen shot 2016-08-11 at 11 02 42" src="https://cloud.githubusercontent.com/assets/19697899/17599367/8dae170c-5fb3-11e6-9b28-558d2659692e.png">

**Comment by contreras-jorgev** [comment]
Assigned to William

**Comment by willianet97** [comment]
Done!
